# github: [nu11secur1ty]
patreon: nu11secur1ty
# sourceforge: nu11secur1ty
custom: ["https://www.patreon.com/posts/33882568"]
custom: ["https://sourceforge.net/p/insmod-block/code/ci/master/tree/", sourceforge.net]

