# github: [nu11secur1ty]
patreon: nu11secur1ty
custom: ["https://www.patreon.com/posts/33882568"]
custom: ["https://sourceforge.net/p/insmod-block/code/ci/master/tree/", sourceforge.net]

custom: ["https://www.nu11secur1ty.com/", "https://github.com/nu11secur1ty"]
custom: ["https://www.paypal.com/donate/?hosted_button_id=ZPQZT5XMC5RFY"]
